local M = {}

local font_presets = {
  "JetBrainsMono Nerd Font",
  "FiraCode Nerd Font",
  "Hack Nerd Font",
  "Iosevka Nerd Font",
  "MesloLGS Nerd Font",
}

local state_path = vim.fn.stdpath("state") .. "/control_center_state.json"
local plugins_state_path = vim.fn.stdpath("data") .. "/control_center_plugins.json"
local user_plugins_path = vim.fn.stdpath("config") .. "/lua/plugins/control_center_user.lua"

local default_state = {
  theme = nil,
  font_family = "JetBrainsMono Nerd Font",
  font_size = 14,
  neovide_scale = 1.0,
  options = {
    relativenumber = true,
    wrap = true,
    spell = false,
    virtual_text = false,
    tabstop = 2,
    shiftwidth = 2,
    expandtab = true,
  },
}

local state = vim.deepcopy(default_state)

local function notify(msg, level)
  vim.notify(msg, level or vim.log.levels.INFO, { title = "Control Center" })
end

local function read_json(path, fallback)
  if vim.fn.filereadable(path) ~= 1 then return fallback end

  local ok_read, lines = pcall(vim.fn.readfile, path)
  if not ok_read or not lines then return fallback end
  if not lines or vim.tbl_isempty(lines) then return fallback end

  local ok, decoded = pcall(vim.json.decode, table.concat(lines, "\n"))
  if not ok or type(decoded) ~= "table" then return fallback end
  return decoded
end

local function write_json(path, payload)
  local dir = vim.fn.fnamemodify(path, ":h")
  vim.fn.mkdir(dir, "p")
  local encoded = vim.json.encode(payload)
  vim.fn.writefile(vim.split(encoded, "\n"), path)
end

local function save_state()
  write_json(state_path, state)
end

local function ensure_user_plugins_file(repos)
  vim.fn.mkdir(vim.fn.fnamemodify(user_plugins_path, ":h"), "p")
  local lines = {
    "-- Auto-generated by Control Center",
    "-- Edit from Control Center > Tools and Package Managers",
    "return {",
  }

  for _, repo in ipairs(repos) do
    table.insert(lines, string.format("  { %q },", repo))
  end

  table.insert(lines, "}")
  vim.fn.writefile(lines, user_plugins_path)
end

local function get_user_plugins()
  local repos = read_json(plugins_state_path, {})
  if type(repos) ~= "table" then repos = {} end
  return repos
end

local function save_user_plugins(repos)
  write_json(plugins_state_path, repos)
  ensure_user_plugins_file(repos)
end

local function select_menu(prompt, items)
  vim.ui.select(items, {
    prompt = prompt,
    format_item = function(item)
      return item.label
    end,
  }, function(choice)
    if choice and choice.action then choice.action() end
  end)
end

local function ask_input(prompt, default, on_confirm)
  vim.ui.input({ prompt = prompt, default = default or "" }, function(value)
    if value and value ~= "" then on_confirm(value) end
  end)
end

local function current_font_size()
  local guifont = vim.o.guifont or ""
  return tonumber(guifont:match(":h(%d+)")) or 14
end

local function set_font_size(size)
  local target = math.max(8, math.min(42, size))
  local guifont = vim.o.guifont or ""

  if guifont == "" then
    vim.o.guifont = "JetBrainsMono Nerd Font:h" .. target
  elseif guifont:find(":h%d+") then
    vim.o.guifont = guifont:gsub(":h%d+", ":h" .. target, 1)
  else
    vim.o.guifont = guifont .. ":h" .. target
  end

  state.font_size = target
  save_state()

  notify("Text size set to " .. target)
end

local function current_font_family()
  local guifont = vim.o.guifont or ""
  if guifont == "" then return "JetBrainsMono Nerd Font" end
  return guifont:match("^(.-):") or guifont
end

local function set_font_family(family)
  local size = current_font_size()
  vim.o.guifont = family .. ":h" .. size
  state.font_family = family
  state.font_size = size
  save_state()
  notify("Font set to " .. family)
end

local function adjust_text_size(delta)
  if vim.g.neovide then
    local scale = tonumber(vim.g.neovide_scale_factor) or 1.0
    local next_scale = math.max(0.6, math.min(2.2, scale + (delta * 0.1)))
    vim.g.neovide_scale_factor = next_scale
    state.neovide_scale = next_scale
    save_state()
    notify("Text scale set to " .. string.format("%.1fx", next_scale))
    return
  end

  set_font_size(current_font_size() + delta)
end

local function reset_text_size()
  if vim.g.neovide then
    vim.g.neovide_scale_factor = 1.0
    state.neovide_scale = 1.0
    save_state()
  end
  set_font_size(14)
end

local function toggle_diagnostic_text()
  local cfg = vim.diagnostic.config()
  local next_state = not cfg.virtual_text
  vim.diagnostic.config({ virtual_text = next_state })
  state.options.virtual_text = next_state
  save_state()
  notify("Diagnostics text " .. (next_state and "enabled" or "disabled"))
end

local function toggle_inlay_hints()
  if not vim.lsp.inlay_hint then
    notify("Inlay hints not supported by this Neovim version", vim.log.levels.WARN)
    return
  end

  local enabled = false
  pcall(function()
    enabled = vim.lsp.inlay_hint.is_enabled({ bufnr = 0 })
  end)

  pcall(function()
    vim.lsp.inlay_hint.enable(not enabled, { bufnr = 0 })
  end)

  notify("Inlay hints " .. ((not enabled) and "enabled" or "disabled"))
end

local function apply_theme(theme)
  local ok = pcall(vim.cmd, "colorscheme " .. theme)
  if not ok then
    notify("Could not apply theme: " .. theme, vim.log.levels.WARN)
    return
  end

  state.theme = theme
  save_state()
  notify("Theme set to " .. theme)
end

local function set_tab_size(value)
  local n = tonumber(value)
  if not n or n < 1 or n > 12 then
    notify("Tab size must be between 1 and 12", vim.log.levels.WARN)
    return
  end

  vim.o.tabstop = n
  vim.o.shiftwidth = n
  state.options.tabstop = n
  state.options.shiftwidth = n
  save_state()
  notify("Tab size set to " .. n)
end

local function set_expandtab(value)
  vim.o.expandtab = value
  state.options.expandtab = value
  save_state()
  notify(value and "Spaces enabled" or "Tabs enabled")
end

local function open_language_menu()
  select_menu("Language and Code Actions", {
    {
      label = "Code Action",
      action = function() vim.lsp.buf.code_action() end,
    },
    {
      label = "Rename Symbol",
      action = function() vim.lsp.buf.rename() end,
    },
    {
      label = "Go to Definition",
      action = function() vim.lsp.buf.definition() end,
    },
    {
      label = "Find References",
      action = function() vim.lsp.buf.references() end,
    },
    {
      label = "Format File",
      action = function()
        local ok, conform = pcall(require, "conform")
        if ok then
          conform.format({ lsp_fallback = true })
        else
          vim.lsp.buf.format({ async = true })
        end
      end,
    },
  })
end

local function open_project_menu()
  select_menu("Project and Workspace", {
    { label = "Toggle File Explorer", action = function() vim.cmd("NvimTreeToggle") end },
    {
      label = "Find File",
      action = function()
        local ok, tb = pcall(require, "telescope.builtin")
        if ok then tb.find_files() end
      end,
    },
    {
      label = "Search in Project",
      action = function()
        local ok, tb = pcall(require, "telescope.builtin")
        if ok then tb.live_grep() end
      end,
    },
    {
      label = "Show Problems Panel",
      action = function()
        vim.diagnostic.setqflist({ open = true })
      end,
    },
    {
      label = "Open Integrated Terminal",
      action = function()
        vim.cmd("ToggleTerm direction=float")
      end,
    },
    {
      label = "Open Git UI",
      action = function() vim.cmd("LazyGit") end,
    },
  })
end

local function open_ide_preferences_menu()
  select_menu("IDE Preferences", {
    {
      label = "Set Tab Size",
      action = function()
        ask_input("Tab size: ", tostring(vim.o.tabstop), set_tab_size)
      end,
    },
    {
      label = "Use Spaces",
      action = function() set_expandtab(true) end,
    },
    {
      label = "Use Tabs",
      action = function() set_expandtab(false) end,
    },
    {
      label = "Toggle Relative Line Numbers",
      action = function()
        vim.o.relativenumber = not vim.o.relativenumber
        state.options.relativenumber = vim.o.relativenumber
        save_state()
        notify("Relative numbers " .. (vim.o.relativenumber and "enabled" or "disabled"))
      end,
    },
    {
      label = "Toggle Wrap",
      action = function()
        vim.o.wrap = not vim.o.wrap
        state.options.wrap = vim.o.wrap
        save_state()
        notify("Wrap " .. (vim.o.wrap and "enabled" or "disabled"))
      end,
    },
    {
      label = "Toggle Spell Check",
      action = function()
        vim.o.spell = not vim.o.spell
        state.options.spell = vim.o.spell
        save_state()
        notify("Spell check " .. (vim.o.spell and "enabled" or "disabled"))
      end,
    },
    { label = "Toggle Diagnostics Text", action = toggle_diagnostic_text },
    { label = "Toggle Inlay Hints", action = toggle_inlay_hints },
  })
end

local function open_mason_packages_menu()
  select_menu("Mason Package Actions", {
    {
      label = "Install Mason Package",
      action = function()
        ask_input("Package name (e.g. lua-language-server): ", "", function(name)
          vim.cmd("MasonInstall " .. name)
        end)
      end,
    },
    {
      label = "Uninstall Mason Package",
      action = function()
        local ok, registry = pcall(require, "mason-registry")
        if not ok then
          notify("Mason registry not available", vim.log.levels.WARN)
          return
        end

        local installed = registry.get_installed_package_names()
        if #installed == 0 then
          notify("No Mason packages installed")
          return
        end

        vim.ui.select(installed, { prompt = "Uninstall package" }, function(choice)
          if choice then vim.cmd("MasonUninstall " .. choice) end
        end)
      end,
    },
  })
end

local function open_plugins_menu()
  select_menu("Plugin Actions", {
    { label = "Open Plugin Manager", action = function() vim.cmd("Lazy") end },
    {
      label = "Install Plugin by Repo",
      action = function()
        ask_input("GitHub repo (owner/name): ", "", function(repo)
          if not repo:match("^[%w%._-]+/[%w%._-]+$") then
            notify("Invalid repo format. Use owner/name", vim.log.levels.WARN)
            return
          end

          local repos = get_user_plugins()
          if vim.tbl_contains(repos, repo) then
            notify(repo .. " is already in your managed plugin list")
            return
          end

          table.insert(repos, repo)
          table.sort(repos)
          save_user_plugins(repos)
          vim.cmd("Lazy sync")
          notify("Added plugin " .. repo .. " and started sync")
        end)
      end,
    },
    {
      label = "Remove Managed Plugin",
      action = function()
        local repos = get_user_plugins()
        if #repos == 0 then
          notify("No Control Center managed plugins to remove")
          return
        end

        vim.ui.select(repos, { prompt = "Remove plugin" }, function(choice)
          if not choice then return end

          local next_repos = {}
          for _, repo in ipairs(repos) do
            if repo ~= choice then table.insert(next_repos, repo) end
          end

          save_user_plugins(next_repos)
          vim.cmd("Lazy sync")
          notify("Removed plugin " .. choice .. " and started sync")
        end)
      end,
    },
  })
end

local function open_appearance_menu()
  select_menu("Appearance", {
    {
      label = "Theme Picker",
      action = function()
        local schemes = vim.fn.getcompletion("", "color")
        table.sort(schemes)
        vim.ui.select(schemes, { prompt = "Choose theme" }, function(choice)
          if choice then apply_theme(choice) end
        end)
      end,
    },
    {
      label = "Theme Toggle (light/dark)",
      action = function()
        local ok, base46 = pcall(require, "base46")
        if ok and base46.toggle_theme then
          base46.toggle_theme()
          state.theme = vim.g.colors_name
          save_state()
        else
          vim.cmd("Telescope themes")
        end
      end,
    },
    {
      label = "Choose Font Family",
      action = function()
        vim.ui.select(font_presets, {
          prompt = "Choose font family",
          format_item = function(item)
            local marker = (item == current_font_family()) and " *" or ""
            return item .. marker
          end,
        }, function(choice)
          if choice then set_font_family(choice) end
        end)
      end,
    },
    { label = "Text Size +", action = function() adjust_text_size(1) end },
    { label = "Text Size -", action = function() adjust_text_size(-1) end },
    { label = "Reset Text Size", action = reset_text_size },
    {
      label = "Set Neovide Opacity",
      action = function()
        ask_input("Opacity (0.3 - 1.0): ", tostring(vim.g.neovide_opacity or 0.9), function(value)
          local n = tonumber(value)
          if not n or n < 0.3 or n > 1.0 then
            notify("Opacity must be between 0.3 and 1.0", vim.log.levels.WARN)
            return
          end
          vim.g.neovide_opacity = n
          notify("Opacity set to " .. n)
        end)
      end,
    },
  })
end

local function open_tools_menu()
  select_menu("Tools and Package Managers", {
    { label = "Plugin Actions", action = open_plugins_menu },
    { label = "Mason Package Actions", action = open_mason_packages_menu },
    { label = "Open Mason UI", action = function() vim.cmd("Mason") end },
    { label = "Treesitter Manager", action = function() vim.cmd("TSInstallInfo") end },
    { label = "LSP Client Info", action = function() vim.cmd("LspInfo") end },
    { label = "Health Check", action = function() vim.cmd("checkhealth") end },
  })
end

local function open_navigation_menu()
  select_menu("Navigation and Search", {
    {
      label = "Command Palette (Telescope Commands)",
      action = function()
        local ok, tb = pcall(require, "telescope.builtin")
        if ok then tb.commands() end
      end,
    },
    {
      label = "Find File",
      action = function()
        local ok, tb = pcall(require, "telescope.builtin")
        if ok then tb.find_files() end
      end,
    },
    {
      label = "Global Search",
      action = function()
        local ok, tb = pcall(require, "telescope.builtin")
        if ok then tb.live_grep() end
      end,
    },
    {
      label = "Open Buffers",
      action = function()
        local ok, tb = pcall(require, "telescope.builtin")
        if ok then tb.buffers() end
      end,
    },
    {
      label = "Keymaps",
      action = function()
        local ok, tb = pcall(require, "telescope.builtin")
        if ok then tb.keymaps() end
      end,
    },
  })
end

function M.open()
  select_menu("Control Center", {
    { label = "Appearance", action = open_appearance_menu },
    { label = "IDE Preferences", action = open_ide_preferences_menu },
    { label = "Language and Code", action = open_language_menu },
    { label = "Project and Workspace", action = open_project_menu },
    { label = "Tools and Package Managers", action = open_tools_menu },
    { label = "Navigation and Search", action = open_navigation_menu },
  })
end

local function apply_state()
  state = vim.tbl_deep_extend("force", vim.deepcopy(default_state), read_json(state_path, {}))

  vim.o.relativenumber = state.options.relativenumber
  vim.o.wrap = state.options.wrap
  vim.o.spell = state.options.spell
  vim.o.tabstop = state.options.tabstop
  vim.o.shiftwidth = state.options.shiftwidth
  vim.o.expandtab = state.options.expandtab

  vim.diagnostic.config({ virtual_text = state.options.virtual_text })

  if state.font_family and state.font_size then
    vim.o.guifont = string.format("%s:h%d", state.font_family, state.font_size)
  end

  if vim.g.neovide then
    vim.g.neovide_scale_factor = state.neovide_scale or 1.0
  end

  if state.theme and state.theme ~= "" then
    pcall(vim.cmd, "colorscheme " .. state.theme)
  end

  ensure_user_plugins_file(get_user_plugins())
end

function M.setup()
  if vim.g.control_center_setup_done then return end
  vim.g.control_center_setup_done = true

  apply_state()

  vim.api.nvim_create_user_command("ControlCenter", function()
    M.open()
  end, { desc = "Open GUI Control Center" })
end

return M
